services:
  # Server container
  nginx:
    container_name: pull-nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/api
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - ${DOCKER_PUBLIC_PORT:-8006}:80
    links:
      - client
      - php
    depends_on:
      - client
      - php
    restart: unless-stopped
    networks:
      - pull-network

  # PHP FastCGI Process Manager container
  php:
    container_name: pull-php
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/api
    restart: unless-stopped
    networks:
      - pull-network
    links:
      - elasticsearch
      - redis

  # Client container
  client: 
    container_name: pull-client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    restart: unless-stopped
    networks:
      - pull-network

  # Client container
  redis:
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
      - ./docker/redis/backup:/backup
    #ports:
      #- 6379:6379
    container_name: 'pull-redis'

# Networks
networks:
  pull-network:
    driver: bridge
    external: false
