version: "3.9"
services:
  mongodb:
    image: mongo:5.0.6
    container_name: dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: IamDev@@246357
    # command: --serviceExecutor adaptive
    ports:
      - "27017:27017"
    volumes:
      - "./config/mongod.conf:/data/configdb/mongod.conf:ro"
      - "./data:/data/db"
      - "./log:/var/log/mongodb"
    command: ["/usr/bin/mongod", "-f", "/data/configdb/mongod.conf"]
    restart: always
    # ulimits:
    #   memlock:
    #      soft: -1
    #      hard: -1      
    networks:
      - dev-network
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
volumes:
  log: null
networks:
  dev-network:
    driver: bridge
